version: '3.1'
services:
    app:
        build: .
        ports:
            - 3000:3000
        links:
            - "redis.example.com:redis"
        networks:
            - back-tier
    redis:
        image: redis:latest
        networks:
            - back-tier
    redis.example.com:
        image: redis:latest
        networks:
            - extra-net
networks:
    back-tier:
    extra-net:
